### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by dribba**
Added a default .gitignore

### CODE REVIEW

**Comment by 2m** [comment]
Thank you for the contribution. I would recommend to setup a [global git ignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) on your machine with all the common ignores. In that case you will not have to add same ignores to every repository you create or clone.

**Comment by dribba** [comment]
Thanks for the suggestion. Correct me if I'm wrong but, this is template is used when creating a new project using the `activator new` command, in most cases those projects will be put in a repository and shared. Setting global ignores fixes the problem in MY machine, but not everyone else using the repository.

**Comment by 2m** [comment]
I would argue that every developer should have these ignores set up in their local machines. After all proposed ignore file contains entries for ide/editor/build tool specific files which need to be ignored for almost every scala/java (even python in this PR case) project.

These entries are *not* specific to this particular project.

**Comment by dribba** [comment]
Yes, I used this https://github.com/typesafehub/activator-hello-akka/blob/master/.gitignore as an example, seemed to be a very equivalent project to this one.
I just followed the logic that most generated projects include a .gitignore so you don't have to understand how the build process, or for example sbt, works in order to put this in a repository. 
I was surprised that I had to search on github for an example of an sbt project's .gitignore and wanted to save other devs from this.
Thanks for the feedback though!

**Pull request closed without merging**
