### PR TITLE
Updated the version of Akka and ScalaTest. 

### PR DESCRIPTION
**Pull request by gavinbaumanis**
Updated the version of Akka and ScalaTest. 
Added code comments for greater clarity.

### CODE REVIEW

**Comment by patriknw** [comment]
Hi @VRanga000,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

http://www.lightbend.com/contribute/cla

**Comment by patriknw** [comment]
sorry @VRanga000, ignore that

**Comment by patriknw** [comment]
Hi @gavinbaumanis,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

http://www.lightbend.com/contribute/cla

**Comment by patriknw** [comment]
@gavinbaumanis This template is moving to https://github.com/akka/akka-scala-seed.g8
Could you submit a PR there also (or there instead)?

**Comment by gavinbaumanis** [comment]
Hi Patrik, Please find the CLA attached.
I will re-create the PR at the new location.
[GavinBaumanis_Lightbend_CLA.pdf](https://github.com/typesafehub/activator-akka-scala-seed/files/697608/GavinBaumanis_Lightbend_CLA.pdf)

**Pull request closed without merging**
