### PR TITLE
Update to the newest library versions.

### PR DESCRIPTION
**Pull request by iref**
It would be great to have up-to-date versions of scala and libraries in this template as this template is one of activator default templates.

I updated Scala and libraries to following version:
* SBT 0.13.12
* Scala 2.11.8
* Akka 2.4.9
* Scalatest 3.0.0

### CODE REVIEW

**Comment by patriknw** [comment]
@iref Thanks for making the update. We just released Akka 2.4.10. Can you please update the PR with that also.

@corruptmemory Alright that we update this?

**Comment by ktoso** [comment]
LGTM, thanks @iref !

**Comment by iref** [comment]
@patriknw Sure thing. Congratulations on new release :)

**Comment by gavinbaumanis** [comment]
I should have checked here first! - I just did the same updates and then came here to create a pull request for the changes!
I don't know if it matters at all - but I also included build.properties in mine to ensure we had the latest version of SBT, being used.

Would you like me to add it?

**Comment by 2m** [comment]
LGTM

**Pull request merged**
